planetshooting/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("website.urls", namespace="website")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact"),
]

website/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

now = timezone.now()

class SlideshowImages(models.Model):
    date_added = models.DateField(default=now)
    title = models.CharField(max_length=150)
    image = models.FileField(upload_to="slideshows", max_length=150)
    text = models.TextField()

    def __str__(self):
        return self.title

class Querys(models.Model):
    date_added = models.DateField(default=now)
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    phone = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name

website/views.py
from django.shortcuts import render

from .models import SlideshowImages, Querys


def index(request):
    sliderImages = SlideshowImages.objects.all()

    return render(request, "index.html", {
    "sliderImages":sliderImages,
    })

def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        q = Querys(name=name, email=email, phone=phone, message=message)
        q.save()
        return render(reques, "contact.html", {
        "flag":True
        })

    else:
        return render(request, "contact.html", {

        })

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
     <head>
     <title>{% block title %}{% endblock title %} - Planet Shooting</title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="{% static "images/favicon.ico" %}" type="image/x-icon">
     <link rel="shortcut icon" href="{% static "images/favicon.ico" %}" type="image/x-icon" />
     <link rel="stylesheet" href="{% static "css/camera.css" %}">
     <link rel="stylesheet" href="{% static "css/style.css" %}">
     <link rel="stylesheet" href="{% static "css/custom.css" %}">
     <script src="{% static "js/jquery.js" %}"></script>
     <script src="{% static "js/jquery-migrate-1.2.1.js" %}"></script>
     <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
	   <script src="{% static "js/script.js" %}"></script>
     <script src="{% static "js/jquery.equalheights.js" %}"></script>
     <script src="{% static "js/jquery.ui.totop.js" %}"></script>
     <script src="{% static "js/superfish.js" %}"></script>
     <script src="{% static "js/jquery.mobilemenu.js" %}"></script>
     <script src="{% static "js/camera.js" %}"></script>
     <script src="{% static "js/TMForm.js" %}"></script>
     <script src="{% static "js/jquery-ui.js" %}"></script>
     <script src="{% static "js/jquery.ui.datepicker.js" %}"></script>
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="{% static "js/jquery.mobile.customized.min.js" %}"></script>
     <!--<![endif]-->
     <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
   		<script src="js/html5shiv.js"></script>
    	<link rel="stylesheet" type="text/css" media="screen" href="css/ie.css">
    <![endif]-->
        <script>
            $(document).ready(function(){
                jQuery('#camera_wrap').camera({
                    loader: true,
                    pagination: true,
                    minHeight: '175',
                    thumbnails: false,
                    height: '48.43%',
                    caption: true,
                    navigation: true,
                    fx: 'blindCurtainSliceTop'
                });
                /*Back to Top*/
                $().UItoTop({ easingType: 'easeOutQuart' });
                $("#datepicker").datepicker();
             });
        </script>
     </head>

     <body id="top">

       {% include "header.html" %}

       {% block content %}
       {% endblock content %}

       {% include "footer.html" %}

      </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Contact Us
{% endblock title %}

{% block content %}

<!--===================content===========================-->

    <div class="container">
        <div class="divider1"></div>
        <div class="row">
        <div class="grid_8">
        <h3>How to Find Us</h3>
            <div class="grid_5 alpha">
               <div class="map">
                <figure>
                 <iframe class="map_c" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Brooklyn,+New+York,+NY,+United+States&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=61.282355,146.513672&amp;ie=UTF8&amp;hq=&amp;hnear=Brooklyn,+Kings,+New+York&amp;ll=40.649974,-73.950005&amp;spn=0.01628,0.025663&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
                </figure>
                </div>
            </div>
            <div class="grid_3 omega">
            <div class="add">
            <h4>The Company Name Inc.</h4>
                <address>
                    <dl>
                    <dt>
                        <span>8901 Marmora Road,</span><br><span>Glasgow, D04 89GR.</span>
                    </dt>
                        <dd><span>Freephone: </span>+1 800 559 6580</dd>
                        <dd><span>Telephone:</span>+1 800 603 6035</dd>
                        <dd><span>FAX:</span>+1 800 889 9898</dd>
                    </dl>
                    <span>E-mail:&nbsp;</span><a href="#">mail@demolink.org</a>
                </address>
                 <address>
                    <dl>
                    <dt>
                        <span>9863 - 9867 Mill Road,</span><br><span>Cambridge, MG09 99HT.</span>
                    </dt>
                        <dd><span>Freephone: </span>+1 800 559 6580</dd>
                        <dd><span>Telephone:</span>+1 800 603 6035</dd>
                        <dd><span>FAX:</span>+1 800 889 9898</dd>
                    </dl>
                    <span>E-mail:&nbsp;</span><a href="#">mail@demolink.org</a>
                </address>
              </div>
            </div>
            </div>
            <div class="grid_4">
            <h3>Contact Form</h3>
                <form id="form">
                    <div class="success_wrapper">
                        <div class="success-message">Contact form submitted</div>
                    </div>
                    <label class="name">
                        <input type="text" placeholder="Name:" data-constraints="@Required @JustLetters" />
                        <span class="empty-message">*This field is required.</span>
                        <span class="error-message">*This is not a valid name.</span>
                    </label>
                    <label class="email">
                        <input type="text" placeholder="E-mail:" data-constraints="@Required @Email" />
                        <span class="empty-message">*This field is required.</span>
                        <span class="error-message">*This is not a valid email.</span>
                    </label>
                    <label class="phone">
                        <input type="text" placeholder="Phone:" data-constraints="@Required @JustNumbers"/>
                        <span class="empty-message">*This field is required.</span>
                        <span class="error-message">*This is not a valid phone.</span>
                    </label>
                    <label class="message">
                        <textarea placeholder="Message:" data-constraints='@Required @Length(min=20,max=999999)'></textarea>
                        <span class="empty-message">*This field is required.</span>
                        <span class="error-message">*The message is too short.</span>
                    </label>
                    <div class="clear"></div>
                    <div class="btns">
                        <a class="link1" href="#" data-type="reset">Clear</a>
                        <a class="link1" href="#" data-type="submit">Send</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="divider2"></div>
    </div>

{% endblock content %}

templates/footer.html
{% load staticfiles %}

<figure>
    <iframe class="map_wide" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Brooklyn,+New+York,+NY,+United+States&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=61.282355,146.513672&amp;ie=UTF8&amp;hq=&amp;hnear=Brooklyn,+Kings,+New+York&amp;ll=40.649974,-73.950005&amp;spn=0.01628,0.025663&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
</figure>

<!--=====================footer=========================-->

<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="grid_3 fright">
                <ul class="list1">
                    <li><a href="#">Events Schedule</a></li>
                    <li><a href="#">Hunting</a></li>
                    <li><a href="#">Firearms</a></li>
                    <li><a href="#">Training</a></li>
                    <li><a href="#">Membership</a></li>
                    <li><a href="#">Contacts </a></li>
                </ul>
            </div>
            <div class="grid_3 fright">
                <ul class="list1">
                    <li><a href="#">google plus</a></li>
                    <li><a href="#">flickr</a></li>
                    <li><a href="#">Dribble</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Skype</a></li>
                </ul>
            </div>
             <div class="grid_6 fleft">
                <h1><a href="index.html"><img src="{% static "images/logo.png" %}" alt="" class="logo"></a></h1>
                <div class="copy"><span>Designed by <a href="http://www.delhinerds.com" target="_blank">Delhi Nerds</a>. Planet Shooting&nbsp;&nbsp;&bull;&nbsp;&nbsp;&copy;</span>&nbsp;&nbsp;<span id="copyright-year"></span>&nbsp;&nbsp;&bull;
                <a href="index-6.html">Privacy Policy</a></div>
            </div>
        </div>
    </div>
</footer>
</div>

templates/header.html
{% load staticfiles %}

<!--========================header=============================-->
<div class="box">
    <header id="header">
    <div class="container">
    <div class="row">
        <div class="grid_4">
            <h1><a href="{% url "website:index" %}"><img src="{% static "images/logo.png" %}" alt="" class="logo"></a></h1>
        </div>
        <div class="grid_8">
            <nav>
                <ul class="sf-menu">
                    <li class="current"><a href="{% url "website:index" %}">Home</a>
                        <ul>
                            <li><a href="#">Events Schedule</a></li>
                            <li><a href="#">Hunting</a></li>
                            <li><a href="#">Firearms</a>
                                <ul>
                                    <li><a href="#">Latest</a></li>
                                    <li><a href="#">Archive</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Training</a></li>
                            <li><a href="#">Membership</a></li>
                            <li><a href="#">Contacts</a></li>
                       </ul>
                    </li>
                    <li><a href="index-1.html">About</a></li>
                    <li><a href="index-2.html">Services</a></li>
                    <li><a href="index-3.html">News</a></li>
                    <li><a href="index-4.html">Blog</a></li>
                    <li><a href="index-5.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>
    </div>
    </header>
    <div class="clear"></div>

templates/index-1.html
<!DOCTYPE html>
<html lang="en">
     <head>
     <title>About</title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico" type="image/x-icon">
     <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
     <link rel="stylesheet" href="css/style.css">
     <script src="js/jquery.js"></script>
     <script src="js/jquery-migrate-1.2.1.js"></script>
     <script src="js/jquery.easing.1.3.js"></script>
	 <script src="js/script.js"></script>
     <script src="js/jquery.equalheights.js"></script>
     <script src="js/jquery.ui.totop.js"></script>
     <script src="js/superfish.js"></script>
     <script src="js/jquery.mobilemenu.js"></script>
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->
     <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
   		<script src="js/html5shiv.js"></script>
    	<link rel="stylesheet" type="text/css" media="screen" href="css/ie.css">
    <![endif]-->
        <script>
            $(document).ready(function(){
                /*Back to Top*/
                $().UItoTop({ easingType: 'easeOutQuart' });
             });
        </script>
     </head>

<body id="top">

<!--========================header=============================-->
<div class="box">
    <header id="header">
    <div class="container">
    <div class="row">
        <div class="grid_4">
            <h1><a href="index.html"><img src="images/logo.png" alt=""></a></h1>
        </div>
        <div class="grid_8">
            <nav>
                <ul class="sf-menu">
                    <li><a href="index.html">Home</a>
                        <ul>
                            <li><a href="#">Events Schedule</a></li>
                            <li><a href="#">Hunting</a></li>
                            <li><a href="#">Firearms</a>
                                <ul>
                                    <li><a href="#">Latest</a></li>
                                    <li><a href="#">Archive</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Training</a></li>
                            <li><a href="#">Membership</a></li>
                            <li><a href="#">Contacts</a></li>
                       </ul>
                    </li>
                    <li class="current"><a href="index-1.html">About</a></li>
                    <li><a href="index-2.html">Services</a></li>
                    <li><a href="index-3.html">News</a></li>
                    <li><a href="index-4.html">Blog</a></li>
                    <li><a href="index-5.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>
    </div>
    </header>
    <div class="clear"></div>

<!--===================content===========================-->

    <div class="container">
            <div class="divider1"></div>
        <div class="row">
            <div class="grid_3">
                <div class="thumb1">
                    <h3>What We Do</h3>
                    <img src="images/page2_img1.jpg" alt="">
                    <p>Integer sem mauris.Cras lectus urna, venenatis sit amet ipsum in; dignissim ultrifeugiat volutpat, dui erat lacinia purus, sed iaculis diam nunc a elit. </p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
            <div class="grid_3">
                <div class="thumb1">
                    <h3>Our Mission</h3>
                    <img src="images/page2_img2.jpg" alt="">
                    <p>Praesent laoreet nisl scelerisque nisi lobortis, non condimentum lorem euismod. Ut pretium risus in metus luctus, sit amet faucibus tortor lobortis. </p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
            <div class="grid_3">
                <div class="thumb1">   
                    <h3>Why Choose Us</h3>
                    <img src="images/page2_img3.jpg" alt="">
                    <p>Vivamus sit amet mi nec risus pulvinar laoreet nisl scelerisque nisi lobortis, non ut pretium risus in metus luctus, sit amet ibus tortor lobortis.</p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
            <div class="grid_3">
                <div class="thumb1">   
                    <h3>Did You Know?</h3>
                    <img src="images/page2_img4.jpg" alt="">
                    <p>Sit amet mi nec risus pulvinar accumsan nec ultricies erat. Praesent laoreet nisl sceleris entum lorem euismod. Ut pretium risus in tus luctus, sit amet.</p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
        </div>
        <div class="divider"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="grid_8">
                <h3>Our Advantages</h3>
                <div class="wrap">
                <section class="section">
                    <div class="grid_1 alpha">
                        <div class="circle">1.</div>
                    </div>
                    <div class="grid_7 omega">
                        <a href="#" class="link2">Vestibulum gravida lacinia sapien at malesuada.</a>
                        <p>Condimentum at mattis non, iaculis nec purus. Fusce et placerat cursus ante. Ut facilisis enim lectus, rhonc us tristique justo aliquet at. Donec ac ultricies justo, ut pharetra neque. Sed eu gravida purus. Ut vitae ellentesque venenatis ac eros sed luctus! Nullam at sem eget dolor.</p>
                    </div>
                </section>
                <section class="section">
                    <div class="grid_1 alpha">
                        <div class="circle">2.</div>
                    </div>
                    <div class="grid_7 omega">
                        <a href="#" class="link2">Quisque augue mauris, sollicitudin id leo et; rhoncus elem. </a>
                        <p>Fusce et placerat cursus ante. Ut facilisis enim lectus, rhoncus tristique justo aliquet at. Donec ac ultricies justo, ut pharetra neque. Sed eu gravida purus. Ut vitae ellentesque venenatis ac eros sed luctus! Nullam at sem eget dolor dictum convallis vitae eu dolor.</p>
                    </div>
                </section>
                <section class="section">
                    <div class="grid_1 alpha">
                        <div class="circle">3.</div>
                    </div>
                    <div class="grid_7 omega">
                        <a href="#" class="link2">Suscipit magna ante, rhoncus porta dui ferment.</a>
                        <p>Mattis non, iaculis nec purus. Fusce et placerat cursus ante. Ut facilisis enim lectus, rhoncus tristique justo aliquet at. Donec ac ultricies justo, ut pharetra neque. Sed eu gravida purus. Ut vitae ellentesque venenatis ac eros sed luctus! Nullam at sem dictum.</p>
                    </div>
                </section>
                </div>   
            </div>
            <div class="grid_4">
                <h3>Testimonials</h3>
                <blockquote class="quote">
                    <p>Phasellus tellus dui, condimentum at mattis non, iaculis nec purus. Fusce et placerat cursus ante. Ut facilisis enim lectus, rhoncus tristique justo aliquet at. Donec ac ultricies justo, ut pharetra neque. Sed vitae commodo neque. </p><br>
                    <div>Mark Johnson</div>
                    <a href="#">info@demolink.org</a>
                </blockquote>
                <blockquote class="quote">
                    <p>Fusce id quam suscipit, vestibulum massa nec, blandit purus. Sed commodo laoreet tortor, at suscipit lectus malesuada quis. Pellentesque a nisi eget nisi consequat ultricies. Nunc pulvinar, nisi vel faucibus adipiscing, mauris.</p><br>
                    <div>Olivia Grosh</div>
                    <a href="#">info@demolink.org</a>
                </blockquote>
            </div>
        </div>
        <div class="divider2"></div>
    </div>

<!--=====================footer=========================-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="grid_3 fright">
                    <ul class="list1">
                        <li><a href="#">Events Schedule</a></li>
                        <li><a href="#">Hunting</a></li>
                        <li><a href="#">Firearms</a></li>
                        <li><a href="#">Training</a></li>
                        <li><a href="#">Membership</a></li>
                        <li><a href="#">Contacts </a></li>
                    </ul>
                </div>
                <div class="grid_3 fright">
                    <ul class="list1">
                        <li><a href="#">google plus</a></li>
                        <li><a href="#">flickr</a></li>
                        <li><a href="#">Dribble</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Skype</a></li>
                    </ul>
                </div> 
                 <div class="grid_6 fleft">
                    <h1><a href="index.html"><img class="logo2" src="images/logo2.png" alt=""></a></h1>
                    <div class="copy"><span>shooting club&nbsp;&nbsp;&bull;&nbsp;&nbsp;&copy;</span>&nbsp;&nbsp;<span id="copyright-year"></span>&nbsp;&nbsp;&bull;
                    <a href="index-6.html">Privacy Policy</a> </div>
                </div>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Home
{% endblock title %}

{% block content %}


<!--======================slider=========================-->

        <div class="slider_wrapper">
            <div id="camera_wrap" class="">
              {% for each in sliderImages %}
                <div data-src="{{each.image.url}}">
                <div class="camera_caption">
                    <div class="title">{{each.title}}</div>
                    <div class="title1">{{each.text|safe}}</div>
                    <!-- <div class="border"><a href="#" class="link">read more</a></div> -->
                </div>
                </div>
              {% endfor %}
            </div>
        </div>
    <div class="clear"></div>

<!--===================content===========================-->

    <div class="container">
        <div class="row">
            <div class="grid_4">
                <div class="thumb">
                    <div class="col1"></div>
                    <h2>Training</h2>
                    <img src="{% static "images/page1_img1.jpg" %}" alt="">
                    <p>Aenean nonummy endrit mauris. Phasellus porta. Fusce suscipit varius m sociis nue penat ibus et magnis dis par.</p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
            <div class="grid_4">
                <div class="thumb">
                    <div class="col2"></div>
                    <h2>Club</h2>
                    <img src="{% static "images/page1_img2.jpg" %}" alt="">
                    <p>Fusce suscipit varius m sociis naque patibus et magnis dis parient tes nascetur ridicu mus. Nulla dui. Fusce feugiat malesuada odio.</p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
            <div class="grid_4">
                <div class="thumb">
                     <div class="col3"></div>
                    <h2>Members</h2>
                    <img src="{% static "images/page1_img3.jpg" %}" alt="">
                    <p>Fusce feugiat malesuada odiorbi nunc odio gravida atcursus necuctus a lorem. Maecenas tristique orci ac sem. </p>
                    <a href="#" class="link1">view more</a>
                </div>
            </div>
        </div>
             <div class="divider"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="grid_4">
                <h3>Services</h3>
                <ul class="list">
                    <li><a href="#">Fusce feugiat malesuada odior</a></li>
                    <li><a href="#">Odio gravida atcursus necuctus a lorem </a></li>
                    <li><a href="#">Maecenas tristique orci ac sem </a></li>
                    <li><a href="#">Duis ultricies pharetra mag</a></li>
                    <li><a href="#">Donec accumsan malesuada orci</a></li>
                    <li><a href="#">Donec sit amet eros</a></li>
                    <li><a href="#">Lorem ipsum dolor sit amet con</a></li>
                </ul>
                <a href="#" class="link1">view more</a>
            </div>
            <div class="grid_4">
                <h3>Welcome</h3>
                <div class="text"><p>Fusce suscipit varius m sociis naque ptibus et magnis dis parient tes nascetur ridicu mus. Nulla dui. Fusce <i>feugiat malesuada</i> odiorbi odio gravida atcursus nec uctus a lorem. Maeceas trisis ultri cies pharetra magnanec accumsan malesuada orc inec sit amet eros. </p><br>
                <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit. Mauris fermentum dictum magna.ed aoreet aliquam leo. Ut tellus dolor dapibus eget eleme ntum vel cursus eleifend elit. </p></div>
                <a href="#" class="link1">view more</a>
            </div>
            <div class="grid_4">
                <h3>Calendar</h3>
                <div id="datepicker"></div>
            </div>
        </div>
    </div>

{% endblock content %}